/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_named_data_jni_psync_PSync_PartialProducer */

#ifndef _Included_net_named_data_jni_psync_PSync_PartialProducer
#define _Included_net_named_data_jni_psync_PSync_PartialProducer
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
